In [1]:
import tensorflow as tf

#  Initialization

In [2]:
x = tf.constant(4,shape=(1,1)) # Making a scalar tensor
x

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[4]])>

In [3]:
x = tf.constant([[1,2,3],[2,3,4]]) #Making a 2 x 3 matrix
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]])>

In [4]:
x = tf.ones(4,1)
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [5]:
x = tf.eye(3,3) #Identity element
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

##  You can make random and uniform distribution

In [6]:
x = tf.random.normal((3,3),mean=0, stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.4222562e+00,  7.7664631e-04, -4.3343338e-01],
       [-6.2284887e-01,  2.2181220e+00,  1.7153214e+00],
       [-1.1220124e+00, -4.2018986e-01, -8.6669970e-01]], dtype=float32)>

In [7]:
x = tf.random.uniform((3,3),minval=-10,maxval=20)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-4.238905 , -5.8654284, 12.696602 ],
       [ 8.920599 , 11.788704 , 18.14305  ],
       [-3.6127272,  3.9428482, -1.3383636]], dtype=float32)>

##  You can also do ranges just like python

In [8]:
x = tf.range(start=2, limit=100, delta=2)
x

<tf.Tensor: shape=(49,), dtype=int32, numpy=
array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])>

##  You can also use cast to switch between dtypes

In [9]:
x = tf.cast(x,tf.float32)
x

<tf.Tensor: shape=(49,), dtype=float32, numpy=
array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 52.,
       54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76., 78.,
       80., 82., 84., 86., 88., 90., 92., 94., 96., 98.], dtype=float32)>

# Mathematical operations 

In [10]:
x= tf.constant([1,2,3])
y = tf.constant([9,8,7])



In [11]:
z=x+y
z=x-y
z=x/y
z =x*y
z = tf.tensordot(x,y,axes=1) # This is for the dot product
z = x**3 # This is for elementwise exponentiation


###  Matrix multiplication

In [12]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z =x@y  # tf.matmul(x,y) can also do it
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.06047612, -0.48364234,  0.8176762 , -0.64649135],
       [-1.0854893 ,  1.3985375 , -0.45867157,  1.4390795 ]],
      dtype=float32)>

##  Indexing of tensors

In [13]:
x = tf.constant([1,3,4,2,5,6,4,3,4,2,4,6,8,7,4,0,3,2,1,9])

In [14]:
x[:] # prints all
x[1:] # Prints all but the fisrt element
x[2:5] # Prints from index 2 to 5 and crops the rest
x[::-1] # Prints in the reverse other
x[::2] # Prints all but skips one element after printing one


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 4, 5, 4, 4, 4, 8, 4, 3, 1])>

###  Getting specific indexes

In [15]:
indexes = tf.constant([2,4,5,3])

x_index = tf.gather(x, indexes)

In [16]:
x_index

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 2])>

###  Indexing for matrix

In [17]:
x = tf.constant([[1,2,3],
                [2,3,4],
                [3,4,5],
                [4,5,6],
                [5,6,7]])

In [18]:
x[0,:] #prints only the first row

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [19]:
x[0:4] # Print from teh first to the specified number

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])>

#  Reshaping

In [20]:
x = tf.range(9)

In [21]:
x = tf.reshape(x,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

### Transposing

In [22]:
x = tf.transpose(x, perm=(1,0))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>