In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
a = np.arange(1,101)
b = np.arange(501,601)

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Creating some data to split

In [4]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

#  Spliting the data

In [5]:
train_test_split(a)

[array([ 8, 38, 75, 99, 32, 49, 22, 71,  4, 24, 16, 25, 76, 27,  2, 80, 31,
        47, 81, 51, 21, 68, 63, 53, 89, 97, 84, 23, 78, 70, 93, 95, 36, 90,
        44, 43, 85, 83, 59, 11, 55, 52, 56, 61, 98, 30, 66, 37, 26, 74, 13,
        64, 79, 39, 34, 82, 17, 18, 46, 88,  5, 33, 62, 86, 48, 29,  1, 12,
         6,  3, 14, 73,  9, 50, 69]),
 array([ 92,  20,  87,  10,  96,   7,  58,  15,  41,  77,  35,  91,  65,
         28,  42,  45,  67,  54,  57,  60,  72, 100,  94,  40,  19])]

In [6]:
a_train, a_test = train_test_split(a)

In [7]:
a_test.shape, a_train.shape

((25,), (75,))

#  Changing the default test size

In [8]:
train_test_split(a,test_size=0.2)

[array([ 10,  40,  87,  33,  30,  38,  25,  67,  23,  58,  80,   2,  31,
         85,  18,  94,  82,  98,  20,  88,  76,  34,  24,  64,  68,  84,
          3,  75,  60,  70,  99,   6,  41,  52,  32,  14,  72,  63,   5,
         36,   1,   9,  49,  95,  92,  79,  66,  51,  12,  74,  48,  27,
         46,  39,  78,  91,  62,  42,  15,  21,  77, 100,  26,   4,  44,
         57,  13,  35,  83,  97,  45,  19,  59,  17,  56,  11,   8,  89,
         86,  37]),
 array([93, 55, 73, 16, 47, 81, 71, 53, 28, 50, 65, 69, 22, 43, 61, 90, 29,
         7, 54, 96])]

#  Changing the shuffle 

In [11]:
train_test_split(a,test_size=0.2, random_state = 42)

[array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
         29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
         82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
         90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
         59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
         53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
         93,  52]),
 array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
        78, 13, 32])]

#  You can split more than 1 array at a time

In [12]:
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2, random_state = 42)

In [13]:
a_train, b_train

(array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
         29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
         82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
         90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
         59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
         53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
         93,  52]),
 array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
        529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
        582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
        590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
        559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
        553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
        593, 552]))